# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12e7e19adb312e3bc1edebbda765604e172d98675afe8b5ed647d5c080ddf201ff2976d8852b38ed511f24505c94953039102c481c89a015275a1bf57f61e9b

test:
  secret_key_base: 8e56c2490459ef5161360edc051c9937d97f471c88fe6b2da03401c31ca5d7516352a39488091c445173510a4ba505bf66c438f6d9b89e041b2071187abd4d2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
